core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.dashboard_view, name='dashboard')
]

erp_fs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('users.urls')),
    path('', include('core.urls')),
    path('materials/', include('materials.urls')),
]

materials/urls.py
from django.urls import path
from . import views

app_name = 'materials'

urlpatterns = [
    path('', views.materials_list, name='material_list'),
    path('create/', views.material_create, name='material_create'),
    path('<int:pk>/edit/', views.material_edit, name="material_edit"),
    path('<int:pk>/delete/', views.material_delete, name="material_delete"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from users.models import UserRole


@login_required
def dashboard_view(request):

    user_roles = UserRole.objects.filter(user_id=request.user)

    permissions = {
        'customers' : 0,
        'suppliers': 0,
        'materials' : 0,
        'purchases': 0,
        'sales' : 0,
        'inventory': 0,
        'accounting' : 0,
        'reporting': 0,

    }

    for user_role in user_roles:
        role = user_role.role
        for module in permissions.keys():
            current_permission = getattr(role,module)
            if current_permission > permissions[module]:
                permissions[module] = current_permission


    context = {
      'user': request.user,
      'permissions': permissions,
      'roles': [ur.role.role_name for ur in user_roles],
    }   

    return render(request, 'core/dashboard.html', context)         
# Create your views here.

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}ERP FS{% endblock %}</title>
        <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="bg-gray-100 font-sans">

    <nav class="bg-[#233b6e] text-white shadow-md">
        <div class="container mx-auto px-4 py-4 flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
            <a href="{% url 'dashboard' %}" class="text-2xl font-bold rounded-lg px-2 py-1 transition-all hover:bg-white/10">
                <img src="{% static 'img/Atomo.svg' %}" alt="ERP FS" class="h-8 w-8">
                <span>ERP FS</span>
            </a>

            <div class="relative w-full md:w-1/2">
                <input type="text" id="transaction-input" class="w-full bg-white/20 text-white rounded-full py-2 pl-10 pr-4 focus:outline-none focus:ring-2 focus:ring-white/50 placeholder-gray-300">
            </div>

            <div class="flex items-center space-x-6">
                <div id="nav-links-desktop" class="hidden md:flex space-x-6">

                </div>

                <div class="relative">
                    <button id="user-menu-button" class="flex items-center space-x-2 text-lg font-medium transition-all hover:bg-white/10 p-2 rounded-lg">
                        <span>{{ user.first_name|default:user.username }}</span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-down"><path d="m6 9 6 6 6-6"></path></svg>
                    </button>
                    <div id="user-menu-dropdown" class="user-dropdown-menu absolute right-0 mt-2 w-48 bg-white text-gray-800 rounded-md shadow-lgpy-1 z-50" **hidden**>
                        <a href="#perfil" class="flex items-center px-5 py-2 hover:bg-gray-200">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-user-round"><circle cx="12" cy="10" r="4"/><circle cx="12" cy="12" r="10"/></svg>
                            <span class="ml-2">Profile</span>
                        </a>
                        <a href="{% url 'logout' %}" class="flex items-center px-5 py-2 hover:bg-gray-200">
                           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" x2="9" y1="12" y2="12"/></svg>
                           <span class="ml-2">Logout</span>
                        </a>

                    </div>
                </div>
            </div>

            <div class="hamburger-menu space-y-2 md:hidden cursor-pointer" id="hamburger-btn">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="mobile-menu" class="hidden md:hidden bg-[#233b6e] pb-4 px-4 text-center transition-all duration-300 ease-in-out">
           <div id="nav-links-mobile" class="flex flex-col">

           </div> 
           
           <div class="border-t border-gray-600 mt-4 pt-4">
             <a href = "#perfil" class="block py-2 text-lg font-medium transition-all hover:text-gray-300">Logout</a>
           </div>
        </div>
    </nav>

    <main class="container mx-auto p-8">
        {% block content %}
        {% endblock content %}

    </main>

 <script src="{% static 'js/script.js' %}"></script>

</body>
</html>

core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}

{% block content %}

 <h2 class="text-3xl font-bold text-gray-800 mb-6 border-b-2 border-gray-400 pb-2">Dashboard</h2>
 <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
     {% if permissions.materials > 0  %}
     <a href="{% url 'materials:material_list' %}" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gem-icon lucide-gem"><path d="M10.5 3 8 9l4 13 4-13-2.5-6"/><path d="M17 3a2 2 0 0 1 1.6.8l3 4a2 2 0 0 1 .013 2.382l-7.99 10.986a2 2 0 0 1-3.247 0l-7.99-10.986A2 2 0 0 1 2.4 7.8l2.998-3.997A2 2 0 0 1 7 3z"/><path d="M2 9h20"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Materials</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.materials == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.customers > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-round-icon lucide-users-round"><path d="M18 21a8 8 0 0 0-16 0"/><circle cx="10" cy="8" r="5"/><path d="M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Customers</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.customers == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.suppliers > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-van-icon lucide-van"><path d="M13 6v5a1 1 0 0 0 1 1h6.102a1 1 0 0 1 .712.298l.898.91a1 1 0 0 1 .288.702V17a1 1 0 0 1-1 1h-3"/><path d="M5 18H3a1 1 0 0 1-1-1V8a2 2 0 0 1 2-2h12c1.1 0 2.1.8 2.4 1.8l1.176 4.2"/><path d="M9 18h5"/><circle cx="16" cy="18" r="2"/><circle cx="7" cy="18" r="2"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Suppliers</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.suppliers == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.purchases > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shopping-cart-icon lucide-shopping-cart"><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Purchases</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.purchases == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.sales > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trending-up-icon lucide-trending-up"><path d="M16 7h6v6"/><path d="m22 7-8.5 8.5-5-5L2 17"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Sales</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.sales == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.inventory > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-package2-icon lucide-package-2"><path d="M12 3v6"/><path d="M16.76 3a2 2 0 0 1 1.8 1.1l2.23 4.479a2 2 0 0 1 .21.891V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9.472a2 2 0 0 1 .211-.894L5.45 4.1A2 2 0 0 1 7.24 3z"/><path d="M3.054 9.013h17.893"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Inventory</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.inventory == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.accounting > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chart-no-axes-column-increasing-icon lucide-chart-no-axes-column-increasing"><path d="M5 21v-6"/><path d="M12 21V9"/><path d="M19 21V3"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Accounting</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.accounting == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.reporting > 0  %}
     <a href="#" class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1">
       <div class="flex flex-col items-center text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-file-text-icon lucide-file-text"><path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/><path d="M14 2v5a1 1 0 0 0 1 1h5"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/></svg>
          <h3 class="text-xl font-semibold text-gray-800">Reporting</h3>
          <p class="text-gray-500 text-sm mt-1">{%if permissions.reporting == 1 %}View Only{% else %}Read and write{% endif %}</p>
        </div>   
     </a>
     {% endif %}

     {% if permissions.materials == 0 and permissions.customers == 0 and permissions.suppliers == 0 and permissions.purchases == 0 and permissions.sales == 0 and permissions.inventory == 0 and permissions.accounting == 0 and permissions.reporting == 0 %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-md mt-8">
            <h4 class="font-bold">Ypu don't have permissions assigned</h4>

        </div>
     {% endif %}
 </div>
{% endblock %}